# Generated by Django 5.2.17 on 2026-09-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('200+', '200+ employees')], default='1-10', max_length=10)),
                ('timeline', models.CharField(choices=[('now', 'Ready now'), ('quarter', 'This quarter'), ('exploring', 'Just exploring')], default='exploring', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('organic', 'Organic Search'), ('paid', 'Paid Ads'), ('referral', 'Referral'), ('social', 'Social Media'), ('direct', 'Direct')], default='direct', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
